owl_function_error: Bail out early in the case of recursive errors.
owl_function_adminmsg triggers a lot of code, and so it is possible that
whatever caused an error will also cause owl_function_adminmsg to error
out. Watch for recursive calls to owl_function_error, and bail out early
to prevent infinite looping.