Protect memrchr prototype by !HAVE_DECL_MEMCHR instead of !HAVE_MEMCHR
This fixes
viewwin.c:393:7: warning: implicit declaration of function ‘memrchr’
on platforms where PERL_CFLAGS doesn’t contain -D_GNU_SOURCE.

!HAVE_MEMRCHR means that memrchr is undefined at link time, so we need
to provide our own implementation; but !HAVE_DECL_MEMRCHR means that
memrchr is not declared at compile time, so we need to provide our own
prototype.

http://lists.gnu.org/archive/html/bug-autoconf/2008-12/msg00037.html

Signed-off-by: Anders Kaseorg <andersk@mit.edu>